# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{yacan}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["pokutuna"]
  s.date = %q{2011-04-30}
  s.description = %q{YaCan is a wrapper for Yahoo Japan Text Analysis Web API}
  s.email = %q{popopopopokutuna@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/yacan.rb",
    "lib/yacan/dependency.rb",
    "lib/yacan/keyphrase.rb",
    "lib/yacan/morphem.rb",
    "lib/yacan/yahoo_api.rb",
    "spec/dependency_spec.rb",
    "spec/keyphrase_spec.rb",
    "spec/morphem_spec.rb",
    "spec/spec_helper.rb",
    "spec/test_source/dependency.xml",
    "spec/test_source/keyphrase.xml",
    "spec/yacan_spec.rb",
    "spec/yahoo_api_spec.rb",
    "yacan.gemspec"
  ]
  s.homepage = %q{http://github.com/pokutuna/yacan}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.7.2}
  s.summary = %q{YaCan}
  s.test_files = [
    "spec/dependency_spec.rb",
    "spec/keyphrase_spec.rb",
    "spec/morphem_spec.rb",
    "spec/spec_helper.rb",
    "spec/yacan_spec.rb",
    "spec/yahoo_api_spec.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
    else
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
  end
end

